name: Deploy to AWS

on: 
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm Install

      - name: Install backend dependencies
        run: |
          cd lambda
          npm install

      - name: Build React app
        run: |
          cd frontend
          npm run build
          cd ..

      - name: Deploy frontend to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'sa-east-1'
        run: |
          aws s3 sync ./frontend/build s3://gr-app-bucket --delete

      - name: Package and deploy CloudFormation stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws cloudformation package \
            --template-file template.yaml \
            --s3-bucket gr-app-bucket \
            --output-template-file out.yaml
          aws cloudformation deploy \
            --template-file out.yaml \
            --stack-name grStack \
            --capabilities CAPABILITY_NAMED_IAM